version: '3.8'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    container_name: DjBackend
    depends_on:
      - myredis
      - db
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db:
    image: postgres:latest
    environment: 
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports : 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  myredis:
    image: redis:7.0.14-alpine3.18
    container_name: MyRedisServer
  
  celery:
    build: .
    command: celery -A project worker --loglevel=info
    depends_on:
      - myredis
      - backend

volumes:
  postgres_data:
